# Javascript Node CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-javascript/ for more details
#
version: 2

jobs:
  lint:
    docker:
      - image: circleci/node:10.15
    working_directory: ~/repo
    steps:
      - checkout
      - restore_cache:
          keys:
          - cache-01-dependencies-{{ checksum "package-lock.json" }}
          - cache-01-dependencies-
      - run: npm install
      - run: npm run bootstrap
      - run: npm run lint

  test-unit:
    docker:
      - image: circleci/node:10.15
    working_directory: ~/toolkit
    steps:
      - checkout
      - restore_cache:
          keys:
          - cache-01-dependencies-{{ checksum "package-lock.json" }}
          - cache-01-dependencies-
      - run: npm install
      - run: npm run bootstrap
      - run: npm run test
      - save_cache:
          paths:
            - node_modules
          key: cache-01-dependencies-{{ checksum "package-lock.json" }}

workflows:
  version: 2
  build_and_test:
    jobs:
      - lint
      - test-unit
